#服务配置
server:
  port: 9002
#Spring配置
spring:
  application:
    name: ihrm_system
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true